// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2BR339IMvLcoJJuey__VdFMko6ciSAzg',
    appId: '1:207875424703:web:291ea12c81cf6d575ee10a',
    messagingSenderId: '207875424703',
    projectId: 'flutter-playground-reservation',
    authDomain: 'flutter-playground-reservation.firebaseapp.com',
    storageBucket: 'flutter-playground-reservation.appspot.com',
    measurementId: 'G-W2SDCWHPC3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpvHAqJvar1BXYWVATJmjWkdl4-f96bGQ',
    appId: '1:207875424703:android:e21faf7a2e49acb15ee10a',
    messagingSenderId: '207875424703',
    projectId: 'flutter-playground-reservation',
    storageBucket: 'flutter-playground-reservation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4XcWsAboL8_Dbg8CD6f4wyWmJo2brcCg',
    appId: '1:207875424703:ios:cd1c4b7f820d15f25ee10a',
    messagingSenderId: '207875424703',
    projectId: 'flutter-playground-reservation',
    storageBucket: 'flutter-playground-reservation.appspot.com',
    iosClientId: '207875424703-ce3i6f6hlags62kjcar70vehoov3df8n.apps.googleusercontent.com',
    iosBundleId: 'com.polydou2264.bugil',
  );
}
